mobile_id: on
host: localhost:3000
full_host: http://localhost:3000
number_of_attempt_failed: 5
default_mail_sender: noreply@ilabsea.org
devise_mail_sender: resourcemap@ilabsea.org
mandrill_username: "resourcesmap@ilabsea.org"
mandrill_password: "YkXyniE49DI4vmmB1FbdNg"
notify_alert: on

plugins:
  public_collection: on
  snapshot: on
  channels: on
  reminders: on
  alerts: on
  account_completeness: on
  fred_api: on
